Repository milvus-io/web-content, pull requests merged in 2019-11, with the labels that each got.

#132 Update Troubleshoot topic and add a new index type `IVF_PQ`
  CHANGELOG.md
  assets/FaceSearch_cn.png
  assets/FaceSearch_en.png
  assets/MilvusTypicalApplication_cn.png
  assets/MilvusTypicalApplication_en.png
  assets/Recommendation_cn.png
  assets/Recommendation_en.png
  assets/ads_recommend.png
  assets/ads_recommend_cn.png
  assets/application_arch.png
  assets/application_arch_cn.png
  assets/face_search.png
  assets/monitoring/monitoring.png
  assets/server_config.yaml
  faq/product_faq.md
  reference/application.md
  reference/milvus_config.md
  userguide/monitor.md
  userguide/troubleshoot.md
  zh-CN/faq/product_faq.md
  zh-CN/reference/application.md
  zh-CN/reference/milvus_config.md
  zh-CN/userguide/monitor.md
  zh-CN/userguide/troubleshoot.md
Labels: enhancement

#136 Add release note
  CHANGELOG.md
  reference/application.md
  release/README.md
  release/v0.5.1.md
  zh-CN/reference/application.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.1.md
  zh-CN/userguide/install_milvus.md
Labels: documentation

#137 Release 0.5.1 documentation
  CHANGELOG.md
  reference/application.md
  release/README.md
  release/v0.5.1.md
  zh-CN/reference/application.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.1.md
  zh-CN/userguide/install_milvus.md
Labels: documentation

#138 Update recource config
  reference/milvus_config.md
  zh-CN/reference/milvus_config.md
Labels: documentation

#140 Picture link fix and doc minor updates
  aboutmilvus/overview.md
  assets/datasource.png
  assets/face_search.png
  assets/importdashboard.png
  assets/importjson.png
  assets/milvus_arch.png
  assets/newdashboard.png
  assets/settings.png
  reference/application.md
  release/v0.2.0.md
  release/v0.2.1.md
  release/v0.3.1.md
  release/v0.4.0.md
  userguide/example_code.md
  userguide/install_milvus.md
  userguide/milvus_operation.md
  userguide/monitor.md
  userguide/troubleshoot.md
  zh-CN/aboutmilvus/overview.md
  zh-CN/reference/application.md
  zh-CN/release/v0.2.0.md
  zh-CN/release/v0.2.1.md
  zh-CN/release/v0.3.0.md
  zh-CN/release/v0.4.0.md
  zh-CN/userguide/example_code.md
  zh-CN/userguide/install_milvus.md
  zh-CN/userguide/milvus_operation.md
  zh-CN/userguide/monitor.md
  zh-CN/userguide/troubleshoot.md
Labels: documentation, enhancement

#144 Remove container name settings
  userguide/install_milvus.md
  zh-CN/userguide/install_milvus.md
Labels: documentation

#145 Add release notes
  release/README.md
  release/v0.5.2.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.2.md
Labels: documentation

#146 Add 0.5.2 release notes
  release/README.md
  release/v0.5.2.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.2.md
Labels: documentation

#147 Update picture links
  aboutmilvus/overview.md
  reference/application.md
  reference/comparison.md
  userguide/monitor.md
  zh-CN/aboutmilvus/overview.md
  zh-CN/reference/application.md
  zh-CN/reference/comparison.md
  zh-CN/userguide/monitor.md
Labels: documentation

#148 Update pic links
  aboutmilvus/overview.md
  reference/application.md
  reference/comparison.md
  userguide/monitor.md
  zh-CN/aboutmilvus/overview.md
  zh-CN/reference/application.md
  zh-CN/reference/comparison.md
  zh-CN/userguide/monitor.md
Labels: documentation

#149 Remove NSG
  faq/product_faq.md
  release/v0.5.0.md
  userguide/milvus_operation.md
  zh-CN/faq/product_faq.md
  zh-CN/release/v0.5.0.md
  zh-CN/userguide/milvus_operation.md
Labels: documentation

#151 Update SDK reference
  reference/sdk.md
  zh-CN/reference/sdk.md
Labels: documentation

#152 Add files via upload
  assets/jaegertraces.png
  assets/jaegerui.png
  assets/k8s_arch.png
  assets/mishards.png
Labels: documentation

#153 Add pictures for Mishards
  assets/jaegertraces.png
  assets/jaegerui.png
  assets/k8s_arch.png
  assets/mishards.png
  reference/sdk.md
  zh-CN/reference/sdk.md
Labels: documentation

#154 Change tmp/milvus to opt/milvus
  assets/server_config.yaml
Labels: documentation

#158 Add v0.5.3 release notes
  CHANGELOG.md
  release/README.md
  release/v0.5.3.md
  userguide/example_code.md
  userguide/milvus_operation.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.3.md
  zh-CN/userguide/example_code.md
  zh-CN/userguide/milvus_operation.md
Labels: documentation

#159 Update documentation for v0.5.3
  CHANGELOG.md
  release/README.md
  release/v0.5.3.md
  userguide/example_code.md
  userguide/milvus_operation.md
  zh-CN/release/README.md
  zh-CN/release/v0.5.3.md
  zh-CN/userguide/example_code.md
  zh-CN/userguide/milvus_operation.md
Labels: documentation

#160 Add version compatibility
  release/v0.5.3.md
  userguide/example_code.md
  zh-CN/release/v0.5.3.md
  zh-CN/userguide/example_code.md
Labels: documentation

#162 Add version compatibility in releast notes
  release/v0.5.3.md
  userguide/example_code.md
  zh-CN/release/v0.5.3.md
  zh-CN/userguide/example_code.md
Labels: documentation

#163 Branch 0.5.3
  reference/milvus_config.md
  zh-CN/reference/milvus_config.md
Labels: documentation

#164 Config parameter update
  reference/milvus_config.md
  zh-CN/reference/milvus_config.md
Labels: enhancement

#169 Added more FAQ content to the documentation
  faq/operational_faq.md
  zh-CN/faq/operational_faq.md
Labels: documentation

#170 Fix issue #167 by removing the link to the release notes
  faq/operational_faq.md
  userguide/install_milvus.md
  zh-CN/userguide/install_milvus.md
Labels: documentation

#173 ok~
  reference/comparison.md
Labels: documentation
